"""db_setup

Revision ID: ade634d17b46
Revises: 
Create Date: 2018-06-24 17:55:21.353738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ade634d17b46'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DailyPrice',
    sa.Column('DATE', sa.Date(), nullable=False),
    sa.Column('TOP10_PRICE', sa.Float(), nullable=True),
    sa.Column('MED40_PRICE', sa.Float(), nullable=True),
    sa.Column('SMALL100_PRICE', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('DATE')
    )
    op.create_table('Med40WeeklyRecord',
    sa.Column('DATE', sa.Date(), nullable=False),
    sa.Column('NAME', sa.String(), nullable=False),
    sa.Column('SYMBOL', sa.String(), nullable=True),
    sa.Column('MARKET_CAP_USD', sa.Float(), nullable=True),
    sa.Column('PERCENT_CHANGE_1H', sa.Float(), nullable=True),
    sa.Column('PERCENT_CHANGE_24H', sa.Float(), nullable=True),
    sa.Column('PERCENT_CHANGE_7D', sa.Float(), nullable=True),
    sa.Column('PRICE_USD', sa.Float(), nullable=True),
    sa.Column('INDEX_PORTION', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('DATE', 'NAME')
    )
    op.create_table('Small100WeeklyRecord',
    sa.Column('DATE', sa.Date(), nullable=False),
    sa.Column('NAME', sa.String(), nullable=False),
    sa.Column('SYMBOL', sa.String(), nullable=True),
    sa.Column('MARKET_CAP_USD', sa.Float(), nullable=True),
    sa.Column('PERCENT_CHANGE_1H', sa.Float(), nullable=True),
    sa.Column('PERCENT_CHANGE_24H', sa.Float(), nullable=True),
    sa.Column('PERCENT_CHANGE_7D', sa.Float(), nullable=True),
    sa.Column('PRICE_USD', sa.Float(), nullable=True),
    sa.Column('INDEX_PORTION', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('DATE', 'NAME')
    )
    op.create_table('Top10WeeklyRecord',
    sa.Column('DATE', sa.Date(), nullable=False),
    sa.Column('NAME', sa.String(), nullable=False),
    sa.Column('SYMBOL', sa.String(), nullable=True),
    sa.Column('MARKET_CAP_USD', sa.Float(), nullable=True),
    sa.Column('PERCENT_CHANGE_1H', sa.Float(), nullable=True),
    sa.Column('PERCENT_CHANGE_24H', sa.Float(), nullable=True),
    sa.Column('PERCENT_CHANGE_7D', sa.Float(), nullable=True),
    sa.Column('PRICE_USD', sa.Float(), nullable=True),
    sa.Column('INDEX_PORTION', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('DATE', 'NAME')
    )
    op.create_table('WeeklyFactor',
    sa.Column('DATE', sa.Date(), nullable=False),
    sa.Column('TOP10_FACTOR', sa.Float(), nullable=True),
    sa.Column('MED40_FACTOR', sa.Float(), nullable=True),
    sa.Column('SMALL100_FACTOR', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('DATE')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('WeeklyFactor')
    op.drop_table('Top10WeeklyRecord')
    op.drop_table('Small100WeeklyRecord')
    op.drop_table('Med40WeeklyRecord')
    op.drop_table('DailyPrice')
    # ### end Alembic commands ###
